// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-5PAYxXtHGvxAPp90BNvtBjBDhpJjVj4',
    appId: '1:461974819621:web:92ef98b077f649987d40cc',
    messagingSenderId: '461974819621',
    projectId: 'core-ai-studios',
    authDomain: 'core-ai-studios.firebaseapp.com',
    storageBucket: 'core-ai-studios.firebasestorage.app',
    measurementId: 'G-G4346HB05V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuoRFuGz8gaAWOlcuX7t2vZ8MEk2wvPSM',
    appId: '1:461974819621:android:2e1a6902ecaaa2c17d40cc',
    messagingSenderId: '461974819621',
    projectId: 'core-ai-studios',
    storageBucket: 'core-ai-studios.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZuqwXKpjKu2oR80y60BiZc0QSBB5THEo',
    appId: '1:461974819621:ios:8c87287f957741937d40cc',
    messagingSenderId: '461974819621',
    projectId: 'core-ai-studios',
    storageBucket: 'core-ai-studios.firebasestorage.app',
    iosBundleId: 'com.kafilcodes.coreaistudios.coreAiStudios',
  );
}
